---
- hosts: localhost
  tasks:
    - name: ping task
      ping:
    - name: Output some data
      debug:
        msg: "This is a example hook created on {{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }} \n"
